### ISSUE TITLE
Update flake8 to fix false positive with Python 3.12

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#101]
This issue is a tracking issue for a problem that shows up with older `flake8` versions and Python 3.12. We updated the CI images to use Python 3.12 in the `latest` tag (https://github.com/rapidsai/ci-imgs/pull/188), which is picked up by style check jobs across RAPIDS. See #40 for the broader Python 3.12 tracking issue.

PRs we need to merge:
- [x] https://github.com/rapidsai/cuvs/pull/328
- [x] https://github.com/rapidsai/cuvs/pull/327
- [x] https://github.com/rapidsai/cugraph/pull/4652
- [x] https://github.com/rapidsai/cuml/pull/6070
- [x] https://github.com/rapidsai/cuxfilter/pull/627
- [x] https://github.com/rapidsai/dask-cuda/pull/1385
- [x] https://github.com/rapidsai/kvikio/pull/463
- [x] https://github.com/rapidsai/raft/pull/2435
- [x] https://github.com/rapidsai/cugraph-gnn/pull/42
- [x] https://github.com/rapidsai/cuspatial/pull/1458
- [x] https://github.com/rapidsai/ucx-py/pull/1070
- [x] https://github.com/rapidsai/cugraph-ops/pull/690
- [x] https://github.com/rapidsai/cuopt/pull/2006
- [x] https://github.com/rapidsai/jupyterlab-nvdashboard/pull/205

**Comment by bdice** [comment]
Future steps that could help:

- Update all these repos to use `ruff`. It has autofixes, which would have made this process faster even if `ruff` had the same bug.
- Update pre-commit hooks on a regular basis to pre-empt this kind of problem.

**Comment by jakirkham** [comment]
We discussed this in our meeting today. Sounds like the last piece was resolved was resolved in `jupyterlab-nvdashboard`. Closing this out as resolved

If I've missed something, please feel free to reopen

Thanks all! 🙏

**Comment by jameslamb** [comment]
Yep that's right, this is done. Thanks @jakirkham
