### ISSUE TITLE
upgrade to `nccl>=2.19` across RAPIDS

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#102]
## Description

`wholegraph` nightly conda-cpp-tests `(amd64, rockylinux8, CUDA 11.4)` have been failing with errors like this:

```text
./WHOLEGRAPH_CSR_WEIGHTED_SAMPLE_WITHOUT_REPLACEMENT_TEST: symbol lookup error: /opt/conda/envs/test/bin/gtests/libwholegraph/../../../lib/libwholegraph.so: undefined symbol: ncclCommSplit
sh -c exec "$0" ./WHOLEMEMORY_HANDLE_TEST 
./WHOLEMEMORY_HANDLE_TEST: symbol lookup error: /opt/conda/envs/test/bin/gtests/libwholegraph/../../../lib/libwholegraph.so: undefined symbol: ncclCommSplit
sh -c exec "$0" ./GRAPH_APPEND_UNIQUE_TEST 
```

([build link](https://github.com/rapidsai/wholegraph/actions/runs/10904436197/job/30260869592))

`ncclCommSplit` was first introduced in `nccl==2.18.1-1` ([commit link](https://github.com/NVIDIA/nccl/commit/d97a32fac84f69cbd022ffdc57d5687c760742c7)) and is used unconditionally in `wholegraph`, but `wholegraph` (and other RAPIDS libraries) have a floor of `nccl>=2.9.9`.

In this particular job, `nccl=2.10.3.1` is getting installed.

```text
 + nccl                     2.10.3.1  hcad2f07_0                  rapidsai-nightly     125MB
```

We haven't noticed this in other jobs or other projects' CI because in all of those, `nccl>=2.18.1` is getting installed.

In addition, pytorch 2.3 requires `nccl>=2.19`: https://github.com/rapidsai/build-planning/issues/102#issuecomment-2375595743

Across RAPIDS, we should raise the floor on `nccl` to `>=2.19`.

## Benefits of this work

* prevents a source of runtime errors when using RAPIDS ML libraries
* allows testing `wholegraph` in a CUDA 11.4 environment again

## Acceptance Criteria

* all RAPIDS libraries with explicit `nccl` dependencies are pinned to `nccl>=2.19`

## Approach

1. create a branch in https://github.com/rapidsai/shared-workflows adding the test job that's failing in `wholegraph` nightlies to the PR matrices
2. update `wholegraph`'s pinnings, open a PR with CI pointed at that branch, and confirm that CI passes
3. point `wholegraph` CI back at `branch-24.10` of `shared-workflows`, delete that `shared-workflows` branch
4. put up PRs with similar pins across all of the RAPIDS libraries with direct `nccl` dependencies
5. merge all those PRs (can be in any order)

```[tasklist]
### Changes
- [x] `wholegraph` (https://github.com/rapidsai/wholegraph/pull/218)
- [x] `raft` (https://github.com/rapidsai/raft/pull/2443)
- [x] `cugraph` (https://github.com/rapidsai/cugraph/pull/4661)
- [x] `cuvs` (https://github.com/rapidsai/cuvs/pull/341)
- [x] `integration` (https://github.com/rapidsai/integration/pull/723)
- [x] `cuopt` (https://github.com/rapidsai/cuopt/pull/2017 ... not critical for RAPIDS 24.10)
```

**Comment by jakirkham** [comment]
In cuGraph, as part of the NumPy 2 upgrade ( https://github.com/rapidsai/cugraph/pull/4615#pullrequestreview-2329731436 ), we noticed [the following logic]( https://github.com/rapidsai/cugraph/blob/1e5b3287e628a5cf8e60da14c25174baf0e5cc1a/ci/test_wheel_cugraph-dgl.sh#L35-L43 )

```bash
# Starting from 2.2, PyTorch wheels depend on nvidia-nccl-cuxx>=2.19 wheel and
# dynamically link to NCCL. RAPIDS CUDA 11 CI images have an older NCCL version that
# might shadow the newer NCCL required by PyTorch during import (when importing
# `cupy` before `torch`).
if [[ "${NCCL_VERSION}" < "2.19" ]]; then
  PYTORCH_VER="2.1.0"
else
  PYTORCH_VER="2.3.0"
fi
```

Given this, am wondering if the minimum NCCL version should be 2.19?

cc @hcho3 (for awareness)

**Comment by jameslamb** [comment]
There are some competing requirements here:

* we want to pin `pytorch>=2.3` to support `numpy>=2`
* `pytorch>=2.3` requires NCCL `>= 2.19`
* `raft`'s floor was just set to `NCCL >=2.18.1.1`, in https://github.com/rapidsai/raft/pull/2443 
* `raft` goes into code freeze for 24.10 in 4 hours
* `raft` is used widely, including in places that don't also use `pytorch` (like `cuml`)
* we generally want the floor for NCCL to be the same across RAPIDS libraries if possible

Given how close it is to 24.10 code freeze for `raft`, I don't think we should raise `raft`'s floor further to 2.19 at this point. I think it's ok for `cugraph` to have a slightly higher floor than `raft` for the 24.10 release... in practice, both libraries have been building against much newer versions of NCCL for a while anyway. For example, look at the most recent successful nightly build of `cugraph` on 24.10... it used NCCL 2.22.3.1:

```text
    nccl:                             2.22.3.1-hd961488_1                        conda-forge   
```

([build link](https://github.com/rapidsai/cugraph/actions/runs/11031255580/job/30637613433#step:7:520))

Here's my proposal:

* 24.10:
  - `raft` stays pinned to `nccl>=2.18.1.1` (because it's about to enter code freeze)
  - `cugraph` pins to `nccl>=2.19` (to support `pytorch>=2.3` and therefore `numpy>2`)
* 24.12
  - all RAPIDS libraries with NCCL pins pins to `nccl>=2.19`

@jakirkham @hcho3 what do you think?

**Comment by hcho3** [comment]
Sounds good to me

**Comment by jakirkham** [comment]
Think if we are planning to bump the minimum across the board, we should go ahead and get it done

Yes we are at code freeze and yes it is not great we are finding this change before then. However I think having the right intended behavior trumps that

Would add that a user not constraining NCCL likely gets a much newer version of NCCL anyways. This is also true of our own testing. So the lower bound is there to prevent unexpected solves and incompatible environments

One last note wholegraph also has a PyTorch dependency. So would need similar treatment to cuGraph

**Comment by jameslamb** [comment]
> However I think having the right intended behavior trumps that

The issue you've found is at the intersection of PyTorch and NCCL. That's why I support bumping the floor up further to `>=2.19` for the libraries that have PyTorch dependencies (and which, conveniently, are not in code freeze yet).

I thought that `raft` did not have a torch dependency... but was wrong about that 🙃 

https://github.com/rapidsai/raft/blob/f37c41c54fc64a4e3689e5a61851ba3821800fee/python/pylibraft/pylibraft/common/outputs.py#L29-L36

So I guess we should do this there too.

**Comment by jameslamb** [comment]
@jakirkham in the interest of time, I started an internal thread about this.

**Comment by jakirkham** [comment]
Thanks James! 🙏

Now that we have a PR for RAFT ( https://github.com/rapidsai/raft/pull/2458 ), should we work on other cases (like Wholegraph)?

**Comment by jameslamb** [comment]
Yes, I'll do that right now.

**Comment by jameslamb** [comment]
Think all the updates we want now have associated PRs:

* [ ] `wholegraph`: https://github.com/rapidsai/wholegraph/pull/223
* [ ] `raft`: https://github.com/rapidsai/raft/pull/2458
* [ ] `cugraph`: should be done together with NumPy 2 updates (https://github.com/rapidsai/cugraph/pull/4615#discussion_r1777315343, cc @hcho3 )
* [ ] `cuvs`: no action required
  - *NCCL was removed in https://github.com/rapidsai/cuvs/pull/341*
* [ ] `integration`: https://github.com/rapidsai/integration/pull/726
* [ ] `cuopt`: no action required
  - *NCCL being removed in https://github.com/rapidsai/cuopt/pull/2017*

**Comment by jakirkham** [comment]
Thanks James! 🙏

Also thank you for organizing that nice list 🙂

**Comment by jameslamb** [comment]
This is complete! Thanks very much for the help @jakirkham @hcho3 @alexbarghi-nv @cjnolet
