### ISSUE TITLE
Remove build isolation in wheel builds

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#108]
## Description

Currently, RAPIDS projects build wheels with build isolation, like `pip wheel .`.

With build isolation, the build tool *(in our case, `pip wheel`)*, creates a virtual environment and installs of the package's build-time dependencies into it. That virtual environment is created at a random location on each build, which means source files included from other wheels *(like the rmm headers from the `librmm` wheel)* are found at a different path on each build in CI.

Path changes lead to cache misses with `sccache`, and therefore longer-running and more memory-intensive builds.

As more of RAPIDS build-time dependencies are provided wheels (e.g. #33), this problem is going to get worse (see https://github.com/rapidsai/build-planning/issues/33#issuecomment-2067555998).

This issue tracks the work of removing build isolation in RAPIDS wheel-building CI jobs.

## Benefits of this work

Better `sccache` hit rate = faster, cheaper CI (contributes to #95).

Stronger guarantees that packages built in CI are actually installed at test time (i.e. would close https://github.com/rapidsai/build-planning/issues/79).

## Acceptance Criteria

* all RAPIDS C/C++ wheel builds in CI build with `--no-build-isolation`

## Approach

Follow the approach from https://github.com/rapidsai/cuspatial/pull/1473, and documented in https://github.com/rapidsai/build-planning/pull/112.

* pure Python? build isolation
* Python + Cython? build isolation
* mostly C/C++? no build isolation

## Notes

These can be done in any order.

```[tasklist]
### Updates
- [x] build-planning: document why we only use build isolation for non-Cython C++ builds (https://github.com/rapidsai/build-planning/pull/112)
- [x] add notes about doing this to the other create-new-C++-wheels issues
- [x] cucim (https://github.com/rapidsai/cucim/pull/792)
- [x] cudf (https://github.com/rapidsai/cudf/pull/17088)
- [x] cugraph *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] cuml *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] cuopt *(nothing to do ... no C/C++ build deps delivered as wheels)*
- [x] cuspatial (https://github.com/rapidsai/cuspatial/pull/1473)
- [x] cuvs *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] cuxfilter (https://github.com/rapidsai/cuxfilter/pull/641)
- [x] dask-cuda (https://github.com/rapidsai/dask-cuda/pull/1400)
- [x] kvikio *(nothing to do ... `libkvikio` does not have build deps delivered as wheels, `kvikio` is only Python + Cython)*
- [x] pynvjitlink *(nothing to do ... no C/C++ build deps delivered as wheels)*
- [x] raft *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] rmm (nothing to do ... `librmm` is header-only and `rmm` is only Python + Cython)
- [x] ucx-py (nothing to do ... only Python + Cython)
- [x] ucxx (https://github.com/rapidsai/ucxx/pull/301)
```

Do the GNN repos last, as some of the `cugraph` repos are currently being shuffled around. See e.g. https://github.com/rapidsai/cugraph-gnn/pull/58#discussion_r1806800793.

```[tasklist]
### GNN repos
- [x] cugraph-gnn *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] cugraph-ops *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
- [x] wholegraph *(nothing to do ... no non-Cython C/C++ deps delivered as wheels)*
```

**Comment by jameslamb** [comment]
I've updated the description to reflect our decision from  an offline conversation:

* pure Python? build isolation
* just Python + Cython? build isolation
* mostly C/C++? no build isolation

And proposed documenting that in the `build-planning` docs: https://github.com/rapidsai/build-planning/pull/112

**Comment by vyasr** [comment]
We shouldn't need to do this for any of the packages that haven't switched to using C++ wheels from other libraries yet, i.e. anything that is still statically linking everything. cugraph, cuml, cuvs, and raft (that may be exhaustive, or I may have missed some) don't have relevant changes yet.

**Comment by jameslamb** [comment]
> _We shouldn't need to do this for ... cugraph, cuml, cuvs, and raft_

Oh interesting. I'd expected that all of them were at least getting RMM headers from the `librmm` wheels, but looking around that appears not to be the case.

<details><summary>evidence of that (click me)</summary>

Looking at recent nightly wheel builds, it seems like all those projects you mentioned are getting rmm via CPM.

```text
-- CPM: Adding package rmm@24.12 (branch-24.12)
```

([pylibcugraph wheel build](https://github.com/rapidsai/cugraph/actions/runs/11554505497/job/32157869684#step:9:245))

([cugraph wheel build](https://github.com/rapidsai/cugraph/actions/runs/11554505497/job/32159689259#step:9:247))

([cuml wheel build](https://github.com/rapidsai/cuml/actions/runs/11522609191/job/32078858185#step:9:19444))

([pylibraft wheel build](https://github.com/rapidsai/raft/actions/runs/11522613699/job/32078882780#step:9:16313))

`cuvs` is slightly different in that it gets it via CPM via `raft`'s CMake, but the result is the same:

```text
-- CPM: raft: Adding package rmm@24.12 (branch-24.12)
```

([cuvs wheel build](https://github.com/rapidsai/cuvs/actions/runs/11460665693/job/31887901003#step:9:11263))

I'm comparing that to other projects like `libcudf`, which are using the `librmm` wheels and therefore have logs like this:

```text
-- CPM: Using local package rmm@24.12.0
```

([cudf wheel build](https://github.com/rapidsai/cudf/actions/runs/11554882065/job/32159052858#step:9:214))

</details>

And any other build-time dependencies those projects are getting via wheels appear to only be reference in Cython code, which we've already said we don't want to use build isolation for (https://github.com/rapidsai/build-planning/issues/108#issuecomment-2432827993).

I'll update the issue description here and add notes about using build isolation to the corresponding issues that track the work for delivering more C++ dependencies in those projects via wheels.

**Comment by vyasr** [comment]
> I'd expected that all of them were at least getting RMM headers from the librmm wheels, but looking around that appears not to be the case.

Yeah we've been following a depth-first rather than breadth-first approach to migrating packages over to use C++ wheels i.e. instead of updating everything to use librmm wheels once they existed we switched kvikio to C++ wheels (using rmm), then cudf (using kvikio and rmm), etc. It makes more sense that way since there's very little benefit to doing this partially until you get to the leaf nodes in our tree anyway (cugraph/cuml using raft).

**Comment by vyasr** [comment]
Yup, that is correct. AFAIK right now we should really only need to make changes to cudf, cuspatial, and kvikio (rmm would need this if it had any dependencies, but since it's our root node it doesn't).

**Comment by jameslamb** [comment]
Great, thank you.

> *For the other libraries we'll have to remember to set this up correctly when we get around to making the C++ wheels.*

Agreed. I'm going to fill out the remaining issues tracking each individual dynamic-wheels thing (e.g. https://github.com/rapidsai/rapids-wheels-planning/issues/66 for `cugraph`) with details about all the things that need to be done for those issues to be considered "done". Should be pretty straightforward and mostly copy-paste, and hopefully that'll make it easier for anyone to pick up the work.

> AFAIK right now we should really only need to make changes to cudf, cuspatial, and kvikio

I think we want ucxx as well... `libucxx` wheels pull in `librmm` and `libucx` wheels at build time ([pyproject.toml](https://github.com/rapidsai/ucxx/blob/b94958dff044a1c063beff0d998e402525f913ca/python/libucxx/pyproject.toml#L64-L65)).

And I think we **don't** want `kvikio`, because it isn't actually pulling in any build dependencies via wheels except `cmake` and `ninja` ([kvikio pyproject.toml](https://github.com/rapidsai/kvikio/blob/40dced5c6b9e3051722fc76554e83f405a462467/python/libkvikio/pyproject.toml#L55-L58)).

**Comment by vyasr** [comment]
You're right about both ucxx and kvikio, thanks.

**Comment by jameslamb** [comment]
I've added notes about this to the "Approach" sections in all the rest of the C++ wheels issues, so I think this can now be closed.

**Comment by leofang** [comment]
Interesting, so sccache depends on the source paths?

**Comment by vyasr** [comment]
Yes.
