### ISSUE TITLE
Update to CCCL 2.7.0

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#115]
This issue tracks the progress of updating RAPIDS to CCCL 2.7.0. The current release candidate is `v2.7.0-rc2`.

**Comment by bdice** [comment]
Testing PRs:
- [x] https://github.com/rapidsai/rapids-cmake/pull/710
- [x] https://github.com/rapidsai/rmm/pull/1715
- [ ] https://github.com/rapidsai/kvikio/pull/531
- [ ] https://github.com/rapidsai/cudf/pull/17233
- [ ] https://github.com/rapidsai/ucxx/pull/313
- [ ] https://github.com/rapidsai/raft/pull/2479
- [ ] https://github.com/rapidsai/cugraph-ops/pull/701
- [ ] https://github.com/rapidsai/cumlprims_mg/pull/216
- [ ] https://github.com/rapidsai/cuspatial/pull/1480
- [ ] https://github.com/rapidsai/cuml/pull/6129
- [ ] https://github.com/rapidsai/cugraph/pull/4743

**Comment by bdice** [comment]
I updated all the repositories above with the latest `branch-25.02`, and built and ran C++ and Python tests for every library manually [still finalizing cuGraph tests at this moment, will update when complete]. Testing locally is easier than running proper CI builds because we'd have to use upstream artifacts from every other library. Given that my local tests are looking good and CI is passing in the CCCL repo with RAPIDS 25.02 (https://github.com/NVIDIA/cccl/pull/2967), I think we can safely move forward here.

These PRs are ready for review and/or could use an extra eye.
- https://github.com/rapidsai/rapids-cmake/pull/710 -- seeing some (unrelated?) fmt / spdlog failures.
- https://github.com/rapidsai/cudf/pull/17233 -- ready for review by cuDF CMake codeowners

Once those two PRs are approved, I think we'll be ready to merge CCCL 2.7.0-rc2 in rapids-cmake, then revert the testing changes in cuDF and merge that. No other PRs have material changes that we need to merge, and the rest can be closed.

**Comment by vyasr** [comment]
@bdice can we close this now? The cuml issue seems like an edge case (whatever is happening there) and not worth keeping this open for.
