### ISSUE TITLE
Use quiet mode with Conda installs

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/build-planning#126]
When installing Conda has progress bars, which are nice as a user installing locally. However when installing on CI, these can be noisy and sometimes get formatted weird. On CI we are better served by using quiet mode with installs, which turns these progress bars off. We can always list the packages after so we can see what was installed in the logs.

To use quiet mode, one can do one of the following:

1. Pass `-q`/`--quiet` to install commands
2. Add to the appropriate config via CLI: `conda config --set quiet false`
3. Or edit `.condarc` directly to include `quiet: false`

**Comment by jameslamb** [comment]
Yes please. I'm not sure what changed recently, but look at this log for example: https://github.com/rapidsai/cugraph-gnn/actions/runs/12198233986/job/34029537082#step:8:141493

141,000+ lines as a result of conda progress bars. Too large to view in the browser, super difficult to read even after downloading the raw content.

**Comment by jakirkham** [comment]
Agreed something changed in how this is showing up for us, which unfortunately looks worse in the logs, but we should have turned this off anyways

**Comment by bdice** [comment]
I don't see `quiet: true` documented in the [conda settings](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/settings.html#settings) but it appears to work in my quick testing. 🤷 I have proposed an update to our CI images to include this flag. https://github.com/rapidsai/ci-imgs/pull/217

**Comment by jakirkham** [comment]
It shows up in [the full `condarc` w/comments in the docs]( https://docs.conda.io/projects/conda/en/latest/configuration.html )

Perhaps it needs better documentation: https://github.com/conda/conda/issues/10811

**Comment by jakirkham** [comment]
Is adding this to our CI images sufficient? Or are there other places we should add this?

**Comment by bdice** [comment]
I think adding this to the CI images is sufficient, yes. I don’t think it is necessary to add this in each repository because the scripts calling conda are all designed for use in our CI images, so they should obey .condarc as modifies in this PR.

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

Closing now that this is enabled in the CI images
