### ISSUE TITLE
Migrate all Python builds from scikit-build to scikit-build-core

### ISSUE THREAD

**Issue by vyasr** [rapidsai/build-planning#2]
RAPIDS libraries are generally built with CMake. To facilitate better integration of the C++ builds with Python builds, we switched from using pure setuptools builds to using scikit-build. This change was crucial to enabling wheels by providing a single standard entrypoint (all the usual Python `pip [install|wheel|etc]` machinery) for building a Python package while also compiling the required C++ components. However, scikit-build's approach to enabling this is fundamentally limited because it relies on plugging into setuptools directly in ways that setuptools only marginally supports. The result is a tool that works most of the time, but has various sharp edges (e.g. incomplete support for MANIFEST.in, broken installations in certain cases, etc) and limitations (an inability to support true editable installations, mixed support for pyproject.toml/setup.py, etc).

The solution is to switch to the newer scikit-build-core builder, a modern standards-based builder that offers the same class of functionality as scikit-build (integrating a Python build with CMake) in a more reliable manner. Doing so will allow us to completely removed deprecated components of our build systems (various uses of setup.py), get rid of workarounds for scikit-build (e.g. the languages we must specify at the CMake level), and get full support for critical features like editable installs.
```[tasklist]
### PRs Contributing To This Effort
- [ ] https://github.com/rapidsai/raft/pull/2051
- [ ] https://github.com/rapidsai/kvikio/pull/325
- [ ] https://github.com/rapidsai/cuspatial/pull/1313
- [ ] https://github.com/rapidsai/cuml/pull/5693
- [ ] https://github.com/rapidsai/cugraph/pull/4053
- [ ] https://github.com/rapidsai/cudf/pull/13531
- [ ] https://github.com/rapidsai/rmm/pull/1287
- [ ] https://github.com/rapidsai/ucxx/pull/146
```

**Comment by jameslamb** [comment]
I'm +1 on this.

For reference, the README has a thorough and direct list of differences between `scikit-build` and `scikit-build-core`: https://github.com/scikit-build/scikit-build-core

**Comment by bdice** [comment]
@vyasr Would it be possible to migrate `cugraph-ops` as well? It seems that repo was missed.

https://github.com/rapidsai/cugraph-ops/blob/96a388691c8d42a9f3b7a56bf6f29d24d8ffe166/pylibcugraphops/pyproject.toml#L20

**Comment by bdice** [comment]
Also, this might not need migrated, but `rapids-cmake` also relies on `scikit-build` as a test dependency.

https://github.com/rapidsai/rapids-cmake/blob/208b0d1240caaca41603fccc10b7ac44aea47477/dependencies.yaml#L146

**Comment by vyasr** [comment]
I chose not to include cugraph-ops in this work because that package uses nanobind instead of Cython for its bindings, so it's not sensitive to rapids-cython changes. I also don't know much about its nanobind usage, and it looks like they do [something bespoke with setting the CMake install directory](https://github.com/rapidsai/cugraph-ops/blob/branch-24.02/pylibcugraphops/setup.py#L63). I'd rather leave that one to the devs to manage the transition since it doesn't impact rapids-cython at all.

**Comment by vyasr** [comment]
Regarding rapids-cmake, I'm pretty sure that dependency is superfluous and can be removed altogether. We never actually launch builds via Python in rapids-cmake. Removed that dependency in https://github.com/rapidsai/rapids-cmake/pull/512.

**Comment by jameslamb** [comment]
I think there's one more block of work that should be done as part of this.

There are some projects with configuration in environment variables that `scikit-build` recognized but `scikit-build-core` does not. From `scikit-build-core`'s migration guide ([docs](https://github.com/scikit-build/scikit-build-core/blob/f8c5798897852e107df0683893de59e15c558baf/docs/migration_guide.md))

> *The `SKBUILD_CONFIGURE_OPTIONS` environment variable is now named `SKBUILD_CMAKE_ARGS` for consistency.*

> *The `SKBUILD_BUILD_OPTIONS` environment variable is not supported. Some specific features are accessible using alternative variables. In particular, use `CMAKE_BUILD_PARALLEL_LEVEL` or `SKBUILD_CMAKE_VERBOSE` to control build parallelism or CMake verbosity directly.*

So I see 3 small pieces of additional work:

* [ ] convert all uses of `SKBUILD_CONFIGURE_OPTIONS` to `SKBUILD_CMAKE_ARGS`
* [ ] convert stuff like `SKBUILD_BUILD_OPTIONS="-j4"` to `CMAKE_BUILD_PARALLEL_LEVEL=4`
* [ ] convert stuff like `SKBUILD_BUILD_OPTIONS="-v"` to `SKBUILD_CMAKE_VERBOSE="true"`

For all projects that have recently cut over to `scikit-build-core`.

---

I didn't find a ton of these from GitHub search ([e.g. this link](https://github.com/search?q=org%3Arapidsai+SKBUILD_BUILD_OPTIONS+NOT+is%3Aarchived&type=code)), but there are a few.

For example, `cuml` cut over to `scikit-build-core` (https://github.com/rapidsai/cuml/pull/5693) but is still using `SKBUILD_BUILD_OPTIONS` to control parallelism ([code link](https://github.com/rapidsai/cuml/blob/c8b990127a650837c731c327aeff84e3ce56a118/build.sh#L291-L293)).

**Comment by vyasr** [comment]
Good catches @jameslamb! Let me work through these. As far as build options we've just been removing the build options everywhere, so I'll do that, and hopefully the configure options are mostly fixed already since those need to be right for everything to work correctly.

**Comment by vyasr** [comment]
These are the remaining issues in repos that have made the scikit-build-core transition. We can close this issue once the following PRs are merged:
- https://github.com/rapidsai/cuml/pull/5714
- https://github.com/rapidsai/cuopt/pull/1615
- https://github.com/rapidsai/cudf/pull/14746

**Comment by vyasr** [comment]
Closing this now. All the associated work has been merged.
