### ISSUE TITLE
Require UCX 1.14.0+

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/build-planning#27]
Recently we dropped `libnuma` from RAPIDS Docker images: https://github.com/rapidsai/miniforge-cuda/issues/22#issuecomment-1979868258

The `libnuma` dependency is added to `conda-forge`'s `ucx` packages starting in `1.14.0`: https://github.com/conda-forge/ucx-split-feedstock/pull/111

To ensure `libnuma` is available, we should make sure that `ucx` is `1.14.0` or newer. Some [potential places to update]( https://github.com/search?q=org%3Arapidsai+path%3Adependencies.yaml+ucx+&type=code )

**Comment by pentschev** [comment]
Given all packages listed depend on UCX-Py, we should anyway be covered for conda: https://github.com/rapidsai/ucx-py/blob/50532d099d564659a8f98043a0164ed49cd30f95/conda/recipes/ucx-py/meta.yaml#L38 .

I think we should just use UCX-Py (and UCXX in the future) as ground truth for UCX version, this prevents us from having to update all other projects. For that I agree we have to update `dependencies.yaml` in the UCX-Py/UCXX repos, but what I'm observing is that doing so does not update cbc/`meta.yaml` when committing, do you know why that happens @jakirkham ?

**Comment by jakirkham** [comment]
As long as they are not using UCX directly, agree with that proposal. Seems easier to implement

The conda-builds changes need to be made manually

If we want `rapidsai-dependency-file-generator` to do this for us, would recommend raising [a new issue]( https://github.com/rapidsai/dependency-file-generator/issues/new )

**Comment by vyasr** [comment]
Please double-check existing issues before raising new ones. In this case, what you want is in rapidsai/dependency-file-generator#7

**Comment by bdice** [comment]
As of https://github.com/rapidsai/ucx-py/pull/1032 and https://github.com/rapidsai/ucxx/pull/205, the `ucx` version pinning in RAPIDS has been updated to 1.15.

I opened https://github.com/rapidsai/integration/pull/704 and https://github.com/rapidsai/raft/pull/2227, which should be enough to close this issue.
