### ISSUE TITLE
Statically link gtest/gbench/nvbench into all C++ test/benchmark executables

### ISSUE THREAD

**Issue by vyasr** [rapidsai/build-planning#32]
Currently we typically dynamically link gtest/gbench/nvbench into our tests/benchmarks. This is unnecessary and it makes these executables harder to consume for people who want to run our tests/benchmarks. We should change this default across RAPIDS. The first step will be updating rapids-cmake to support using gtest statically. Once that is done, we can start rolling out the changes across RAPIDS.

**Comment by robertmaynard** [comment]
PRs to resolve this issue in RAPIDS repos:

- [ ] cudf
- [ ] rmm
- [ ] [raft](https://github.com/rapidsai/raft/pull/2265)
- [ ] [cuml](https://github.com/rapidsai/cuml/pull/5847)
- [ ] cugraph
- [ ] cuvs

**Comment by robertmaynard** [comment]
Closing as RAPIDS has been converted to static gtest/gbench/nvbench
