### ISSUE TITLE
Enable running all pytests in `arm64` builds

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/build-planning#36]
For `arm64` jobs, we currently only run smoke tests that don't test the full coverage on `arm`, the following are all the PRs that will enable running full suite of pytests on `arm64` jobs:

* https://github.com/rapidsai/cuml/pull/5824
* https://github.com/rapidsai/rmm/pull/1510
* https://github.com/rapidsai/cudf/pull/15402
* https://github.com/rapidsai/raft/pull/2248
* https://github.com/rapidsai/cuvs/pull/63
* https://github.com/rapidsai/cucim/pull/717
* https://github.com/rapidsai/ucxx/pull/217
* https://github.com/rapidsai/cuspatial/pull/1365

**Comment by jameslamb** [comment]
Hey @galipremsagar is there any other work remaining for this, or could it be closed?

**Comment by galipremsagar** [comment]
It's just legate-cuml remaining: https://github.com/rapidsai/legate-cuml/pull/13

**Comment by jameslamb** [comment]
I thinking waiting on that particular repo shouldn't block closing this. That's how I'm approaching other RAPIDS-wide things like https://github.com/rapidsai/dependency-file-generator/issues/89.

I'll send you a message internally with some more details on that.
