### ISSUE TITLE
Migrate Conda recipes to `{{ stdlib('c') }}`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/build-planning#39]
The `sysroot*` syntax used currently by RAPIDS recipes is getting phased out

Sample syntax as seen [currently in `librmm`]( https://github.com/rapidsai/rmm/blob/9e6db746f1a4a6361fb9fadf381f749dc52faaea/conda/recipes/librmm/meta.yaml#L26C1-L26C58 ):

`recipe/meta.yaml`:

```yaml
    - sysroot_{{ target_platform }} {{ sysroot_version }}
```

`recipe/conda_build_config.yaml`:

```yaml
sysroot_version:
  - "2.17"
```

<hr>

The recommendation is to move to `{{ stdlib('c') }}` ( https://github.com/conda-forge/conda-forge.github.io/issues/2102 )

Changes would look something like this

`recipe/meta.yaml`:

```diff + yaml
-    - sysroot_{{ target_platform }} {{ sysroot_version }}
+    - {{ stdlib('c') }}
```

`recipe/conda_build_config.yaml`:

```diff + yaml
-sysroot_version:
+c_stdlib_version:
  - "2.17"
```

<hr>

Raising this issue to track making these changes in RAPIDS

**Comment by bdice** [comment]
@jakirkham This seems like an easy change to automate for conda recipes. Let me know if I should work on that.

What should be done about `sysroot` packages in `dependencies.yaml`? https://github.com/rapidsai/rmm/blob/9e6db746f1a4a6361fb9fadf381f749dc52faaea/dependencies.yaml#L91

**Comment by jameslamb** [comment]
@hcho3 I've assigned this to you here since you've been working on it.

**Comment by jakirkham** [comment]
Bradley and I reviewed. We think they look good

Asking OPS for a review. That will likely happen early next week

If OPS approves, we can merge

**Comment by jakirkham** [comment]
These are all now merged. Closing as complete

Thanks Hyunsu for the PRs and everyone for the reviews! 🙏
