### ISSUE TITLE
Add support for CUDA 12.2

### ISSUE THREAD

**Issue by vyasr** [rapidsai/build-planning#6]
This is a meta-issue for tracking support for CUDA 12.2 builds. I'll open separate sub-issues for pip and conda because there is different work that needs to be done for each.
```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/build-planning/issues/7
- [ ] https://github.com/rapidsai/build-planning/issues/8
```

**Comment by ajschmidt8** [comment]
I will update the driver versions on our CI machines early next week to support this task.

I will post back here when that's complete.

**Comment by bdice** [comment]
One of the tasks we'll need to do is to update `dependencies.yaml` to have more generic CUDA major version support. See this PR for an example of what I mean: https://github.com/rapidsai/rmm/pull/1414

**Comment by ajschmidt8** [comment]
> I will update the driver versions on our CI machines early next week to support this task.
> 
> I will post back here when that's complete.

The driver update is complete. All `latest`-labeled machines are now using driver 535.

The documentation page below has been updated to reflect this change:

- https://docs.gha-runners.nvidia.com/runners/#gpu-runners

**Comment by bdice** [comment]
Final tasks are being tracked here: https://github.com/rapidsai/build-planning/issues/7#issuecomment-1957227696

**Comment by bdice** [comment]
The final task is to use CUDA 12.2 for the `latest` tag in CI images. We are going to hold off for a bit before merging that. See: https://github.com/rapidsai/ci-imgs/pull/116#issuecomment-1966580694
