### ISSUE TITLE
Remove unused `setuptools` dependencies

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#62]
## Description

Working on #31, I found that `cudf` was carrying a dependency on `setuptools` that it didn't need. See https://github.com/rapidsai/cudf/pull/15736.

Noticed something similar in `cuml` today: https://github.com/rapidsai/cuml/pull/5901.

I suspect there might be other RAPIDS libraries that also have an unnecessary `setuptools` dependency, left over from earlier approaches to building them.

## Benefits of this work

* removes an unnecessary dependency, with all the benefits that that entails

## Acceptance Criteria

* every `setuptools` dependency across RAPIDS is used

## Approach

Browse through https://github.com/search?q=org%3Arapidsai%20setuptools&type=code.

Repos with `setuptools` declared only in conda build recipes or `dependencies.yaml` (i.e. never directly imported, not referenced in `[build-system]` table in `pyproject.toml`) are good candidates. Add a tasklist here listing the repos to investigate.

For any repos that look like they're carrying around unnecessary `setuptools` dependencies, remove those dependencies.

## Notes

* [x] `cudf` (https://github.com/rapidsai/cudf/pull/15736)
* [x] `cuml` (https://github.com/rapidsai/cuml/pull/5901)
* [x] `cugraph` (https://github.com/rapidsai/cugraph/pull/4448)
* [x] `cuspatial` (https://github.com/rapidsai/cuspatial/pull/1389)
* [x] `kvikio` (https://github.com/rapidsai/kvikio/pull/385)
* [x] `raft` (https://github.com/rapidsai/raft/pull/2343)

**Comment by jameslamb** [comment]
I did one more quick GitHub search, don't see any other cases that need to be addressed. This is complete 😁

**Comment by jakirkham** [comment]
Thanks James! 🙏
