### ISSUE TITLE
Ensure `PARALLEL_LEVEL` variable is set to a suitable value in CI scripts

### ISSUE THREAD

**Issue by jjacobelli** [rapidsai/build-planning#66]
**Problem Statement**
The GHA platform team is deprecating the definition of the `PARALLEL_LEVEL` variable at the runner level. This variable is only used by RAPIDS and is currently defined to the value returned by the `nproc` command on the GHA runner. RAPIDS projects depending on this variable should ensure its defined in CI scripts before removing it from the runners.

**Proposal**
Update the [rapids-configure-sccache](https://github.com/rapidsai/gha-tools/blob/74f6b6d168eadff8ba8dd61d47afb684804caefa/tools/rapids-configure-sccache) GHA tool to define the `PARALLEL_LEVEL` variable to a suitable value:
- While running in CI (`CI = true`), we should set the `PARALLEL_LEVEL` to the value returned by `nproc --all`
- While running in local reproducer (`CI != true`), we should set the `PARALLEL_LEVEL` to the value returned by `nproc --all --ignore 2` to prevent using all CPU cores on dev workstation

**Comment by jjacobelli** [comment]
Setting the `PARALLEL_LEVEL` to `nproc --all` in CI can prevent the runner process from running and crash the runner itself. To prevent this, we should set the `PARALLEL_LEVEL` to `nproc --all --ignore=2` in both CI and not CI envs

**Comment by jjacobelli** [comment]
> I assume the solution here is to add PARALLEL_LEVEL to rapids-configure-sccache and remove it from the shared-workflows below, right?

To be honest, I'm not sure what these `env` lines are doing. We now know that using `env` to access an env variable defined at the runner level is not working and returns an empty string. These lines must be removed.
Related doc: https://docs.github.com/en/actions/learn-github-actions/contexts#env-context

> Do we need PARALLEL_LEVEL set for the test workflows?

AFAIK `PARALLEL_LEVEL` is only used in CPU jobs

**Comment by ajschmidt8** [comment]
Yeah, good point. I just checked the logs below and `PARALLEL_LEVEL` isn't set for the test workflows anyway. So we should be good.

- https://github.com/rapidsai/cudf/actions/runs/9276047599/job/25552739723?pr=15871#step:7:166
