### ISSUE TITLE
Add support for CUDA 12.2 wheels

### ISSUE THREAD

**Issue by vyasr** [rapidsai/build-planning#7]
We would like to start publishing wheels that support versions of CUDA newer than CUDA 12.0. Currently, this requires that we:
- [x] Update CI runners  to use R535 drivers (CUDA 12.2, Long Term Support Branch). @ajschmidt8 will take care of this.
- [x] Update the ci-imgs repo to build images with the desired CUDA versions. This was partially completed in https://github.com/rapidsai/ci-imgs/pull/53, but the ci-wheel and citestwheel images [are currently excluded from the latest CUDA version](https://github.com/rapidsai/ci-imgs/blob/main/matrix.yaml#L36). Moreover, that initial change was for 12.1, and at this point we might as well use 12.2.
- [x] Modify the [wheel shared-workflows](https://github.com/rapidsai/shared-workflows/tree/branch-24.02/.github/workflows) to use the new images in building wheels. ~These jobs [should be set up to continue on error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error)~ ([comment explaining why this is crossed out](https://github.com/rapidsai/shared-workflows/pull/166#issuecomment-1886118955))
- [x] Follow up with different RAPIDS developer teams to address any issues with builds that arise in CUDA 12.x builds. This job will mostly involve coordinating a response from the teams; the assignee of this issue is _not_ responsible for actually fixing said builds.

Once we have 12.2 wheels and conda packaging has caught up, we may wish to revisit the CTK version and go to 12.3. For initial work we will start with 12.2, though.

**Comment by jameslamb** [comment]
> Update the ci-imgs repo to build images with the desired CUDA versions

I believe this is done as of https://github.com/rapidsai/miniforge-cuda/pull/56 and https://github.com/rapidsai/ci-imgs/pull/101.

**Comment by jameslamb** [comment]
Based on my conversations with @bdice over the last few days, we're going to try rolling out `dependencies.yaml` changes similar to https://github.com/rapidsai/rmm/pull/1422 across all RAPIDS repos as a part of this.

Tracking that here.

* [ ] `rmm`
  - https://github.com/rapidsai/rmm/pull/1422
* [ ] `cudf`
  - https://github.com/rapidsai/cudf/pull/14733
* [ ] `dask-cuda`
* [ ] `kvikio` ([repo](https://github.com/rapidsai/kvikio))
* [ ] `ucx-py` ([repo](https://github.com/rapidsai/ucx-py))
* [ ] `cucim` ([repo](https://github.com/rapidsai/cucim))
* [ ] `rapids-cmake` ([repo](https://github.com/rapidsai/rapids-cmake))
* [ ] `ucxx` ([repo](https://github.com/rapidsai/ucxx))
* [ ] `raft` ([repo](https://github.com/rapidsai/raft))
* [ ] `cugraph` ([repo](https://github.com/rapidsai/cugraph))
* [ ] `cugraph-ops` ([repo](https://github.com/rapidsai/cugraph-ops))
* [ ] `cumlprims-mg` ([repo](https://github.com/rapidsai/cumlprims_mg)) 
* [ ] `cuml` ([repo](https://github.com/rapidsai/cuml))
* [ ] `wholegraph` ([repo](https://github.com/rapidsai/wholegraph)) 
* [ ] `cuspatial` ([repo](https://github.com/rapidsai/cuspatial)) 
* [ ] `cuxfilter` ([repo](https://github.com/rapidsai/cuxfilter))

**Comment by jameslamb** [comment]
All the first round of `dependencies.yaml` changes are up (see the PRs linked at https://github.com/rapidsai/build-planning/issues/7#issuecomment-1885379300).

`cuml` and `cuxfilter` have failures I'll look into tomorrow.

I don't have permission to add labels or merge PRs in most of those repos... @ajschmidt8 @bdice could you take a look at those tomorrow whenever you have time?

As those get merged I'll start putting up the PRs that target the CUDA 12.2 `shared-workflows` branch + add CUDA 12.2 entries in `dependencies.yaml` where necessary.

**Comment by vyasr** [comment]
I've added the missing labels etc. Most of those PRs should be good to go.

**Comment by jameslamb** [comment]
> I've added the missing labels etc. Most of those PRs should be good to go.

Thank you! I didn't have permission to add labels in most of those repos. Let me know if you think I should and I can request that access.

**Comment by jameslamb** [comment]
Thanks to everyone for the help with the `dependencies.yaml` PRs! The next piece of this is to put up PRs in those same projects testing CUDA 12.2 builds and tests.

* `shared-workflows` changes: https://github.com/rapidsai/shared-workflows/pull/166
* `rapids-reviser` config I'm using: https://github.com/rapidsai/rapids-reviser/pull/15

Moving the checklist for that from the description of `shared-workflows` PR to here so this issue contains the full history of changes.

I'll keep updating this as those PRs go up, and I'll keep adding PRs as the `dependencies.yaml` changes from https://github.com/rapidsai/build-planning/issues/7#issuecomment-1885379300 are merged.

* [ ] `rmm`
  - https://github.com/rapidsai/rmm/pull/1419
* [ ] `cudf`
* [ ] `dask-cuda`
* [ ] `kvikio` ([repo](https://github.com/rapidsai/kvikio))
* [ ] `ucx-py` ([repo](https://github.com/rapidsai/ucx-py))
* [ ] `cucim` ([repo](https://github.com/rapidsai/cucim))
* [ ] `rapids-cmake` ([repo](https://github.com/rapidsai/rapids-cmake))
* [ ] `ucxx` ([repo](https://github.com/rapidsai/ucxx))
* [ ] `raft` ([repo](https://github.com/rapidsai/raft))
* [ ] `cugraph` ([repo](https://github.com/rapidsai/cugraph))
* [ ] `cugraph-ops` ([repo](https://github.com/rapidsai/cugraph-ops))
* [ ] `cumlprims-mg` ([repo](https://github.com/rapidsai/cumlprims_mg)) 
* [ ] `cuml` ([repo](https://github.com/rapidsai/cuml))
* [ ] `wholegraph` ([repo](https://github.com/rapidsai/wholegraph))
* [ ] `cuspatial` ([repo](https://github.com/rapidsai/cuspatial))
* [ ] `cuxfilter` ([repo](https://github.com/rapidsai/cuxfilter))

**Comment by vyasr** [comment]
> Thank you! I didn't have permission to add labels in most of those repos. Let me know if you think I should and I can request that access.

Probably worth revisiting that question eventually, but not immediately. As of now there aren't many people with wide permissions across RAPIDS outside the ops team. We'll probably want to discuss whether your team should have similar privileges at some point, but I imagine it would be a subset (triage everywhere, not necessarily admin or even write).

**Comment by jameslamb** [comment]
Updated all of the PRs from https://github.com/rapidsai/build-planning/issues/7#issuecomment-1887577440 to target `branch-24.04`.

<details><summary>git commands for the curious (click me)</summary>

```shell
# get branch-24.04
git fetch upstream branch-24.04
git checkout branch-24.04

# update branch-24.04 on my fork
git push origin branch-24.04
# get branch with CUDA 12.2 changes, merge in branch-24.04
git fetch origin test-cuda-12.2
git checkout test-cuda-12.2
git pull origin test-cuda-12.2
git merge -X ours branch-24.04

# update CUDA 12.2 PR
git push origin test-cuda-12.2
```

</details>

**Comment by jameslamb** [comment]
Next steps is changing all those GitHub Actions configs from `{workflow}.yaml@test-cuda-12.2` to `{workflow}.yaml@branch-24.04`.

Put up PRs for those:

Thanks to everyone for the help with the `dependencies.yaml` PRs! The next piece of this is to put up PRs in those same projects testing CUDA 12.2 builds and tests.

* `shared-workflows` changes: https://github.com/rapidsai/shared-workflows/pull/166
* `rapids-reviser` config I'm using: https://github.com/rapidsai/rapids-reviser/pull/15

Moving the checklist for that from the description of `shared-workflows` PR to here so this issue contains the full history of changes.

I'll keep updating this as those PRs go up, and I'll keep adding PRs as the `dependencies.yaml` changes from https://github.com/rapidsai/build-planning/issues/7#issuecomment-1885379300 are merged.

* [ ] `rmm`
  - [ ] https://github.com/rapidsai/rmm/pull/1468
* [ ] `cudf`
  - [ ] https://github.com/rapidsai/cudf/pull/15069
* [ ] `dask-cuda`
  - [ ] https://github.com/rapidsai/dask-cuda/pull/1314
* [ ] `kvikio`
  - [ ] https://github.com/rapidsai/kvikio/pull/343
* [ ] `ucx-py`
  - [ ] https://github.com/rapidsai/ucx-py/pull/1026
* [ ] `cucim`
  - [ ] https://github.com/rapidsai/cucim/pull/702
* [ ] `rapids-cmake`
  - [ ] https://github.com/rapidsai/rapids-cmake/pull/541
* [ ] `ucxx`
  - [ ] https://github.com/rapidsai/ucxx/pull/191
* [ ] `raft`
  - [ ] https://github.com/rapidsai/raft/pull/2189
* [ ] `cugraph`
  - [ ] https://github.com/rapidsai/cugraph/pull/4175
* [ ] `cuml`
  - [ ] https://github.com/rapidsai/cuml/pull/5776
* [ ] `wholegraph`
  - [ ] https://github.com/rapidsai/wholegraph/pull/135
* [ ] `cuspatial`
  - [ ] https://github.com/rapidsai/cuspatial/pull/1343
* [ ] `cuxfilter`
  - [ ] https://github.com/rapidsai/cuxfilter/pull/571
* [ ] private repos

**Comment by jameslamb** [comment]
Last few activities we've identified to finish this work:

* [ ] delete `test-cuda-12.2` branch on https://github.com/rapidsai/shared-workflows
* [x] test CI in https://github.com/rapidsai/integration
  - [x] https://github.com/rapidsai/integration/pull/700
* [ ] add CUDA 12.2 to the install selector in the RAPIDS docs
  - [ ] https://github.com/rapidsai/docs/issues/482
* [ ] update other docs in `rapidsai/docs`
  - [ ] https://github.com/rapidsai/docs/issues/482
* [ ] update `rapidsai/docker` container images
  - [ ] https://github.com/rapidsai/docker/pull/634

**Comment by bdice** [comment]
I'm going to mark this issue as complete, now that we're down to just one task (which we are going to wait before merging). https://github.com/rapidsai/ci-imgs/pull/116#issuecomment-1966580694

We should use #6 for any further discussions, now that this issue (focused on wheels) is complete.
