### ISSUE TITLE
[Platform support] support Ubuntu 24.04

### ISSUE THREAD

**Issue by sisodia1701** [rapidsai/build-planning#74]
### Ubuntu 24.04 support in RAPIDS 24.08

- Currently supported platforms (RAPIDS 24.06) -  `CUDA 12.2`, `Python 3.11`, and `Ubuntu 22.0`4. 
- Latest available platforms  - `CUDA 12.5` (May 2024), `Python 3.12` (October 2023), and `Ubuntu 24.04` (April 2024).

Ubuntu 24.04 is currently blocked. Once **`nvidia/cuda` images for Ubuntu 24.04 are available**, the team can start implementing and add the support.

Once the **`nvidia/cuda` images for Ubuntu 24.04 become available**, the team to initiate the implementation process and integrate support for the new version into RAPIDS.

**Comment by bdice** [comment]
nvidia/cuda images are now available. https://hub.docker.com/r/nvidia/cuda/tags?name=ubuntu24.04

We should work on this for RAPIDS 24.12.

**Comment by bdice** [comment]
I have a PR open to add Ubuntu 24.04 CI images: https://github.com/rapidsai/ci-imgs/pull/195

I also have a draft PR to add Ubuntu 24.04 to our CI testing matrix: https://github.com/rapidsai/shared-workflows/pull/248

**Comment by jameslamb** [comment]
I took the "in RAPIDS 24.08" off the title of this, as that isn't true. We track the target version in a field on the issue.

**Comment by bdice** [comment]
Downstream testing:
- [ ] cudf: https://github.com/rapidsai/cudf/pull/16998)
- [ ] rmm: https://github.com/rapidsai/rmm/pull/1704
  - [ ] Blocked by an unrelated issue in https://github.com/rapidsai/rmm/pull/1706
- [x] kvikio: https://github.com/rapidsai/kvikio/pull/499
- [x] ucx-py: https://github.com/rapidsai/ucx-py/pull/1083
- [ ] ucxx: https://github.com/rapidsai/ucxx/pull/302
- [ ] raft: https://github.com/rapidsai/raft/pull/2471
- [ ] cugraph: https://github.com/rapidsai/cugraph/pull/4725
- [x] cuml: https://github.com/rapidsai/cuml/pull/6113
- [ ] cuvs: https://github.com/rapidsai/cuvs/pull/414
- [x] cuspatial: https://github.com/rapidsai/cuspatial/pull/1477
- [x] cuxfilter: https://github.com/rapidsai/cuxfilter/pull/640
- [x] cucim: https://github.com/rapidsai/cucim/pull/793

**Comment by bdice** [comment]
I opened a few more PRs:
- [ ] https://github.com/rapidsai/docker/pull/717
- [ ] https://github.com/rapidsai/ci-imgs/pull/200
- [ ] https://github.com/rapidsai/docs/pull/554
- [ ] https://github.com/rapidsai/rapids.ai/pull/412

**Comment by bdice** [comment]
glibc requirement updates are done:
- [x] https://github.com/rapidsai/docs/pull/559
- [x] https://github.com/rapidsai/rapids.ai/pull/414
