### ISSUE TITLE
Update UCX pinnings (to support 1.17.0)

### ISSUE THREAD

**Issue by pentschev** [rapidsai/build-planning#77]
To update UCX we must change various different repositories. I hope this issue will be useful for future reference, here are the places we must update:

1. UCX-Py: `dependencies.yaml` and `conda/recipes/ucx-py/meta.yaml`. See https://github.com/rapidsai/ucx-py/pull/1051 for example;
2. UCXX: `dependencies.yaml` and `conda/recipes/ucxx/meta.yaml`. See https://github.com/rapidsai/ucxx/pull/240 for example;
3. Integration: `conda/recipes/versions.yaml`. See https://github.com/rapidsai/integration/pull/712 for example.
4. ucx-wheels: update `VERSION`. See https://github.com/rapidsai/ucx-wheels/pull/10 for example.
5. devcontainers: default version in `matrix.yaml`, available versions in `ucx` feature in `features/src/ucx/devcontainer-feature.json` and the respective feature version in the same file. See https://github.com/rapidsai/devcontainers/pull/338 for example.
  - *and then updating base images used in devcontainers builds for libraries that use UCX*

Notice that we have two different pinnings:

1. `depends_on_ucx_build`: this refers what UCX version should be used to build and must be equal the _minimum_ version we support, for example `ucx==1.15.0` means we build against version 1.15.0 and that's the minimum required version at runtime;
2. `depends_on_ucx_run`: this refers what UCX versions we support running, the minimum version should match at least what's defined in `depends_on_ucx_build` and has no theoretical upper limit, as API/ABI should be compatible, for example `ucx>=1.15.0,<1.18`.

**Comment by jameslamb** [comment]
> *and then updating base images used in devcontainers builds for libraries that use UCX*

Put up PRs here:

* https://github.com/rapidsai/cuvs/pull/262
* https://github.com/rapidsai/cugraph/pull/4562
  - *needed to include this change along with others to unblock CI there*
* https://github.com/rapidsai/raft/pull/2401
* https://github.com/rapidsai/cugraph-ops/pull/680

`cuml` had already been updated:

* https://github.com/rapidsai/cuml/pull/5944

**Comment by jameslamb** [comment]
It looks to me like everything needed for this is complete. @pentschev I'm going to close this. Please do re-open it if I've misunderstood and there's still something remaining.

**Comment by jakirkham** [comment]
Indeed thanks all! 🙏
