### ISSUE TITLE
Switch Conda packages to `.conda` (instead of `.tar.bz2`)

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/build-planning#98]
Currently RAPIDS builds and publishes packages using `.tar.bz2`. However this was revamped in the newer `.conda` packages. The make a few important changes:

1. Use a top-level uncompressed `.zip` file
2. Means all `.conda` packages can be renamed to `.zip` and extracted
3. As `.zip` files allow random access, specific items can be retrieved
4. Metadata is placed in the top-level
    1. Contains info about the `.conda` metadata itself
    2. Package metadata (how it was built, dependencies needed, etc.)
    3. Compressed package contents (currently using Zstd)

This can help with solve times (no need to decompress `.tar.bz2` to find metadata first). It can also help with download sizes & times (we noticed ~30% reduction in size of the legacy `cudatoolkit` when transitioning conda-forge)

<hr>

To make the change, we would simply need to update our `condarc` at build time to include

```yaml
conda_build:
  pkg_format: '2'
```

This can also be done with the following command:

```
conda config --set conda_build.pkg_format '2'
```

<hr>

Also as pointed out by James in comment ( https://github.com/rapidsai/ci-imgs/pull/176#pullrequestreview-2266384030 ) there are a few places where `.tar.bz2` shows up in the RAPIDS org. Of these noted that some were:

* Data files (so not Conda packages)
* Archived repos (so not active)
* Dormant repos (haven't seen activity in years; candidates for archival)
* Forks of upstream repos (in some cases these overlap with the above categories)

Decided to skip the above. In the event we want to revitalize one of these projects, likely this is one of many changes that will be needed.

Of the remainder saw:

* Infrastructure tools
* Shared CI content
* One-off projects

Made a best effort to update these. With some one-off projects, they don't run CI yet; so, we can likely move ahead without those

**Comment by jakirkham** [comment]
It is worth noting that XGBoost Conda packages in RAPIDS are already built in the `.conda` format (for [example]( https://anaconda.org/rapidsai/libxgboost/files ). So we are already making some use of these today

**Comment by jakirkham** [comment]
Think this is all we need: https://github.com/rapidsai/ci-imgs/pull/176

Would be good if others can confirm though

**Comment by jameslamb** [comment]
> think this is all we need

We'll also need to update any places where `*.tar.bz2` or similar is being used to list conda packages. See https://github.com/rapidsai/ci-imgs/pull/176#pullrequestreview-2266384030

**Comment by jakirkham** [comment]
Have made a best effort to submit PRs where appropriate. Included notes on this above. Would be good if someone else can recheck whether we got everything we deem relevant

**Comment by jameslamb** [comment]
I think you got everything, and I've reviewed them all: https://github.com/rapidsai/ci-imgs/pull/176#issuecomment-2318892498

**Comment by jakirkham** [comment]
Think we have what we need in

AIUI gpuci-tools should no longer be used. Though James mentioned offline there might still be a few spots where it is used

If we do want to update gpuci-tools, we have PR: https://github.com/rapidsai/gpuci-tools/pull/37

Will double check next week (after the long weekend) if we want to include that PR too

**Comment by jakirkham** [comment]
Have confirmed we don't need PR: https://github.com/rapidsai/gpuci-tools/pull/37

More details in comment: https://github.com/rapidsai/gpuci-tools/pull/37#issuecomment-2375849708

So have closed it out

Think we are ready for PR ( https://github.com/rapidsai/ci-imgs/pull/176 ). Would recommend we do that after 24.10 ships

**Comment by jakirkham** [comment]
We have just shipped the final piece 🥳

Let's see how this goes

**Comment by jakirkham** [comment]
There were some hiccups due to a couple spots that still needed updates

These were resolved with the help of James and Bradley

More details in issue: https://github.com/rapidsai/shared-workflows/issues/250
